version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: dakwah_user
      POSTGRES_PASSWORD: dakwah_pass
      POSTGRES_DB: dakwah_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dakwah_user -d dakwah_db']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgresql://dakwah_user:dakwah_pass@db:5432/dakwah_db
      JWT_SECRET: change_this_in_production_min_32_chars_long
      JWT_REFRESH_SECRET: change_this_refresh_secret_min_32_chars
      ALLOWED_ORIGIN: http://localhost:3000
      APP_URL: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api/v1
    depends_on:
      - api

volumes:
  postgres_data:
