version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: dakwah_user
      POSTGRES_PASSWORD: dakwah_pass
      POSTGRES_DB: dakwah_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dakwah_user -d dakwah_db']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
