import { GroupLevel, ICCategory, ICType } from '@prisma/client';

export type ICSeedItem = {
  level: GroupLevel;
  category: ICCategory;
  type: ICType;
  number: number;
  title: string;
  materi: string | null;
  sortOrder: number;
};

export const IC_SEED_DATA: ICSeedItem[] = [
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 1,
    title: "Menerapkan adab sebelum dan saat membaca Alquran (1)",
    materi: "Adab membaca Alquran",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 2,
    title: "Membiasakan membaca Alquran dua halaman setiap hari  (2)",
    materi: "Kewajiban Muslim terhadap Alquran",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 4,
    title: "Berusaha menghafal surat Adh-Dhuha sampai surat An-Naas 3",
    materi: "Surat Adh-Dhuha sampai surat An-Nas",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 6,
    title: "Bersikap optimistis 4",
    materi: "Surat Al-Insyirah: Selalu Optimistis",
    sortOrder: 4,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 7,
    title: "Bersemangat melakukan amal kebaikan 5",
    materi: "Surat At-Tin: Semangat beramal saleh",
    sortOrder: 5,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 8,
    title: "Bersemangat dalam menuntut ilmu 6",
    materi: "Surat Al-Alaq: Semangat menuntut ilmu",
    sortOrder: 6,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 10,
    title: "Gemar berteman dengan orang baik 7",
    materi: "Surat Al-Bayyinah: Gemar berteman dengan orang baik",
    sortOrder: 7,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 15,
    title: "Menampilkan sikap bekerjasama dalam kebaikan 8",
    materi: "Surat Al-Ashr: Menggunakan waktu untuk bekerjasama dalam kebaikan",
    sortOrder: 8,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 16,
    title: "Bersemangat dalam bersedekah 9",
    materi: "Surat Al-Humazah: Semangat bersedekah",
    sortOrder: 9,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 24,
    title: "Meyakini Ke-Esa-an Allah swt. 10",
    materi: "Surat Al-Ikhlas: Keesaan Allah swt.",
    sortOrder: 10,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 25,
    title: "Menghindari sikap iri dan dengki 11",
    materi: "Surat Al-Falaq: Bahaya iri dan dengki",
    sortOrder: 11,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 28,
    title: "Berusaha menghafal Hadis 1-10 Arbain An-Nawawi12",
    materi: "Arbain An-Nawawi Hadis no. 1 sampai 10",
    sortOrder: 12,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 29,
    title: "Menghadirkan niat ikhlas dalam setiap perbuatan13",
    materi: "Arbain An-Nawawi Hadis no. 1: Ikhlas",
    sortOrder: 13,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 33,
    title: "Saling menghargai dalam masalah khilafiyah 14",
    materi: "Arbain An-Nawawi Hadis no. 5: Menghargai perbedaan pendapat",
    sortOrder: 14,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 34,
    title: "Menghindari hal-hal yang haram 15",
    materi: "Arbain An-Nawawi Hadis no. 6: Halal dan haram",
    sortOrder: 15,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 38,
    title: "Mengonsumsi makanan yang halal dan thoyyib 16",
    materi: "Arbain An-Nawawi Hadis no. 10: Mencukupkan diri dengan yang halal dan thoyyib",
    sortOrder: 16,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 44,
    title: "Ihsan dalam thoharoh 17",
    materi: "Fikih  Thaharah",
    sortOrder: 17,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 45,
    title: "Melaksanakan shalat lima waktu 18",
    materi: "Fikih shalat wajib",
    sortOrder: 18,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 48,
    title: "Menjalankan puasa ramadhan  19",
    materi: "Fikih puasa",
    sortOrder: 19,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 53,
    title: "Membiasakan berzikir dan berdoa kepada Allah swt. 20",
    materi: "Zikir dan doa",
    sortOrder: 20,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 54,
    title: "Membiasakan istighfar  21",
    materi: "Taubat",
    sortOrder: 21,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 56,
    title: "Berbakti kepada orang tua 22",
    materi: "Bentuk-bentuk bakti kepada orang tua",
    sortOrder: 22,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 3,
    title: "Memiliki keinginan untuk mempelajari Bahasa Alquran",
    materi: "Keistimewaan Bahasa Alquran",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 5,
    title: "Berempati terhadap anak yatim dan orang yang meminta-minta",
    materi: "Surat Adh-Dhuha: Bersyukur ketika mendapat nikmat",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 9,
    title: "Bersemangat meraih Lailatul Qadar",
    materi: "Surat Al-Qadar: Semangat meraih Lailatul Qadar",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 11,
    title: "Meyakini bahwa setiap amal akan dipertanggungjawabkan",
    materi: "Surat Al-Zalzalah: Setiap amal akan dipertanggungjawabkan",
    sortOrder: 4,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 12,
    title: "Mengetahui keutamaan berjuang",
    materi: "Surat Al-'Adiyat: Keutamaan berjuang",
    sortOrder: 5,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 13,
    title: "Meyakini peristiwa-peristiwa yang terjadi pada hari kiamat",
    materi: "Surat Al-Qariah: Kejadian-kejadian pada hari kiamat",
    sortOrder: 6,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 14,
    title: "Mengetahui hakikat kehidupan dunia",
    materi: "Surat At-Takatsur: Hakikat kehidupan dunia",
    sortOrder: 7,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 17,
    title: "Optimistis terhadap masa depan Islam",
    materi: "Surat Al-Fil: Optimistis terhadap masa depan Islam",
    sortOrder: 8,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 18,
    title: "Mengetahui pentingnya memiliki penghasilan",
    materi: "Surat Quraisy: Semangat mencari nafkah",
    sortOrder: 9,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 19,
    title: "Memiliki kepedulian sosial",
    materi: "Surat Al-Ma'un: Kepedulian sosial",
    sortOrder: 10,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 20,
    title: "Memahami pentingnya keseimbangan antara ibadah ritual dengan ibadah sosial",
    materi: "Surat Al-Kautsar: Ibadah ritual dan ibadah sosial",
    sortOrder: 11,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 21,
    title: "Mengetahui sikap moderat dalam Islam",
    materi: "Surat Al-Kafirun: Moderasi dalam Islam",
    sortOrder: 12,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 22,
    title: "Mengetahui hakikat kemenangan",
    materi: "Surat An-Nashr: Hakikat kemenangan",
    sortOrder: 13,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 23,
    title: "Mendukung orang yang berbuat baik",
    materi: "Surat Al-Masad/Al-Lahab: Dukungan kepada orang-orang yang berbuat baik",
    sortOrder: 14,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 26,
    title: "Membiasakan membaca surat Al-Ikhlas, surat Al-Falaq, dan surat An-Naas",
    materi: "Surat An-Nas: Bisikan jahat jin dan manusia",
    sortOrder: 15,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 27,
    title: "Membiasakan bershalawat kepada Rasulullah saw.",
    materi: "Mencintai dan menghormati Rasulullah saw.",
    sortOrder: 16,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 30,
    title: "Mengetahui rukun Iman, rukun Islam, dan Ihsan",
    materi: "Arbain An-Nawawi Hadis no. 2: Islam, Iman, dan Ihsan",
    sortOrder: 17,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 31,
    title: "Mengetahui kesempurnaan Islam",
    materi: "Arbain An-Nawawi Hadis no. 3: Bangunan Islam",
    sortOrder: 18,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 32,
    title: "Mengetahui proses penciptaan manusia",
    materi: "Arbain An-Nawawi Hadis no. 4: Penciptaan manusia",
    sortOrder: 19,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 35,
    title: "Memahami pentingnya nasihat",
    materi: "Arbain An-Nawawi Hadis no. 7: Agama adalah nasihat",
    sortOrder: 20,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 36,
    title: "Mengetahui peran Islam dalam melindungi jiwa dan harta",
    materi: "Arbain An-Nawawi Hadis no. 8: Islam melindungi jiwa dan harta",
    sortOrder: 21,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 37,
    title: "Berusaha melaksanakan kewajiban dalam Islam",
    materi: "Arbain An-Nawawi Hadis no. 9: Patuh pada ajaran Islam",
    sortOrder: 22,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 39,
    title: "Mengetahui aspek-aspek keimanan",
    materi: "Rukun Iman",
    sortOrder: 23,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 40,
    title: "Mengetahui iman kepada Allah swt.",
    materi: "Iman kepada Allah swt.",
    sortOrder: 24,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 41,
    title: "Mengetahui iman kepada kitab-kitab",
    materi: "Beriman kepada Kitab-kitab Allah swt.",
    sortOrder: 25,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 42,
    title: "Mengetahui iman kepada Rasul",
    materi: "Beriman kepada para Rasul",
    sortOrder: 26,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 43,
    title: "Mengetahui pembagian hukum fikih",
    materi: "Hukum dalam fikih",
    sortOrder: 27,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 46,
    title: "Mengetahui fikih shalat sunnah",
    materi: "Fikih shalat sunah",
    sortOrder: 28,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 47,
    title: "Mengetahui fikih shalat jamak dan qashar",
    materi: "Fikih jamak dan qashar shalat",
    sortOrder: 29,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 49,
    title: "Mengetahui hukum zakat",
    materi: "Fikih zakat",
    sortOrder: 30,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 50,
    title: "Mengetahui sirah Nabi Muhammad saw. sejak kelahiran sampai melakukan dakwah secara sembunyi-sembunyi",
    materi: "Sirah Nabawiyah sejak kelahiran sampai dakwah secara sembunyi-sembunyi",
    sortOrder: 31,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 51,
    title: "Mengetahui akhlak Nabi Muhammad saw. sebelum diutus",
    materi: "Akhlak dan sifat Nabi Muhammad saw sebelum diutus sebagai Rasul",
    sortOrder: 32,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 52,
    title: "Membaca ayat-ayat Alquran tentang mengenal Allah swt.",
    materi: "Ayat-ayat mengenal Allah swt. (Bagian satu); Ayat-ayat mengenal Allah swt. (Bagian dua)",
    sortOrder: 33,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 55,
    title: "Memberi salam dan mendoakan sesama muslim",
    materi: "Persaudaraan dalam Islam",
    sortOrder: 34,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEBANGSAAN,
    type: ICType.PRIMER,
    number: 58,
    title: "Memahami Pancasila sebagai Dasar Negara  23",
    materi: "Pancasila sebagai dasar negara",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEBANGSAAN,
    type: ICType.PRIMER,
    number: 60,
    title: "Mengetahui sejarah penyusunan UUD NRI 1945",
    materi: "Sejarah penyusunan UUD NRI 1945",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEBANGSAAN,
    type: ICType.PRIMER,
    number: 62,
    title: "Memahami konsep Bhinneka Tunggal Ika 24",
    materi: "Bhinneka Tunggal Ika",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEBANGSAAN,
    type: ICType.SEKUNDER,
    number: 57,
    title: "Mengetahui konsep demokrasi",
    materi: "Demokrasi",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEBANGSAAN,
    type: ICType.SEKUNDER,
    number: 59,
    title: "Mengetahui konsep negara",
    materi: "Konsep negara",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEBANGSAAN,
    type: ICType.SEKUNDER,
    number: 61,
    title: "Mengetahui sikap moderat",
    materi: "Sikap moderat",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEBANGSAAN,
    type: ICType.SEKUNDER,
    number: 63,
    title: "Mengetahui bahaya korupsi",
    materi: "Bahaya korupsi",
    sortOrder: 4,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEMASYARAKATAN,
    type: ICType.PRIMER,
    number: 64,
    title: "Menampilkan sikap gotong royong, ramah, dan guyub 25",
    materi: "Karakter masyarakat Indonesia",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEMASYARAKATAN,
    type: ICType.PRIMER,
    number: 67,
    title: "Menampilkan perilaku yang baik dalam bertetangga 26",
    materi: "Klasifikasi tetangga dan hak-haknya",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEMASYARAKATAN,
    type: ICType.SEKUNDER,
    number: 65,
    title: "Menampilkan sikap toleransi di masyarakat",
    materi: "Sikap toleransi di masyarakat",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEMASYARAKATAN,
    type: ICType.SEKUNDER,
    number: 66,
    title: "Mengetahui keutamaan kerja-kerja kerelawanan",
    materi: "Kerelawanan",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEMASYARAKATAN,
    type: ICType.SEKUNDER,
    number: 68,
    title: "Mengetahui peran, hak, dan kewajiban anak dalam keluarga",
    materi: "Membangun keluarga",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEORGANISASIAN,
    type: ICType.PRIMER,
    number: 71,
    title: "Berusaha berolah raga secara rutin minimal 30 menit setiap hari 27",
    materi: "Urgensi berolah raga secara rutin dan menjaga kebugaran",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEORGANISASIAN,
    type: ICType.SEKUNDER,
    number: 69,
    title: "Hadir di program Pembinaan minimal 80%",
    materi: "Urgensi Kegiatan Kaderisasi untuk Anggota",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEORGANISASIAN,
    type: ICType.SEKUNDER,
    number: 70,
    title: "Hadir di program Pelatihan minimal 80%",
    materi: null,
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.PRIMER,
    number: 73,
    title: "Memilki konsep diri 28",
    materi: "Kepemimpinan diri",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.PRIMER,
    number: 76,
    title: "Menerapkan Pola Hidup Bersih, Sehat, dan Bugar  29",
    materi: "Pola Hidup Bersih dan Sehat (PHBS)",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.SEKUNDER,
    number: 72,
    title: "Bangga berbahasa Indonesia",
    materi: "Pentingnya keterampilan berbahasa",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.SEKUNDER,
    number: 74,
    title: "Mengetahui konsep mendengar yang efektif",
    materi: "Mendengar efektif",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.SEKUNDER,
    number: 75,
    title: "Mengetahui kiat praktis kreativitas dan inovasi",
    materi: "Kreatifitas dan inovasi",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.SEKUNDER,
    number: 77,
    title: "Mengetahui pentingnya kewirausahaan",
    materi: "Mindset bisnis",
    sortOrder: 4,
  },
  {
    level: GroupLevel.LEVEL_1,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.SEKUNDER,
    number: 78,
    title: "Mampu menggunakan media sosial dengan bijaksana",
    materi: "Etika bermedia sosial",
    sortOrder: 5,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 1,
    title: "Menerapkan adab mendengar bacaan Alquran",
    materi: "Adab dalam mendengar bacaan Alquran",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 2,
    title: "Membiasakan membaca Alquran setengah juz setiap hari sesuai hukum tajwid",
    materi: "Keutamaan membaca Alquran secara rutin",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 4,
    title: "Berusaha menghafal surat An-Naba sampai surat Al-Lail sesuai hukum tajwid",
    materi: "Surat An-Naba sampai surat Al-Lail",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 10,
    title: "Menghindari perbuatan melampaui batas",
    materi: "Surat An-Naziat ayat 34-39: Menghindari perbuatan penghuni neraka",
    sortOrder: 4,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 11,
    title: "Berusaha mengendalikan hawa nafsu",
    materi: "Surat An-Naziat ayat 40-46: Ciri-ciri penghuni surga",
    sortOrder: 5,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 13,
    title: "Bertanggung jawab atas segala perbuatannya",
    materi: "Surat At-Takwir ayat 1-14, dahsyatnya hari kiamat",
    sortOrder: 6,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 16,
    title: "Tidak berbuat curang",
    materi: "Surat Al-Muthaffifin: Tidak berlaku curang",
    sortOrder: 7,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 20,
    title: "Berusaha tazkiyatun nafs dengan mengingat Allah swt.",
    materi: "Surat Al-A'la: Menyucikan diri",
    sortOrder: 8,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 23,
    title: "Bersabar dalam kebaikan",
    materi: "Surat Al-Balad: Bersabar dalam kebaikan",
    sortOrder: 9,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 25,
    title: "Menghindari sikap bakhil",
    materi: "Surat Al-Lail: Larangan berbuat bakhil",
    sortOrder: 10,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 27,
    title: "Berusaha menghafal hadis 11 sampai 25 Arbain An-Nawawi",
    materi: "Arbain An-Nawawi Hadis no. 11 sampai 25",
    sortOrder: 11,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 28,
    title: "Berusaha meninggalkan hal-hal yang meragukan",
    materi: "Arbain An-Nawawi Hadis no. 11: Meninggalkan hal-hal yang meragukan",
    sortOrder: 12,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 29,
    title: "Berusaha meninggalkan hal-hal yang tidak bermanfaat",
    materi: "Arbain An-Nawawi Hadis no. 12: Meninggalkan hal-hal yang tidak bermanfaat",
    sortOrder: 13,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 30,
    title: "Menghindari sikap egois",
    materi: "Arbain An-Nawawi Hadis no. 13: Peduli pada problematika umat",
    sortOrder: 14,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 32,
    title: "Memuliakan orang lain",
    materi: "Arbain An-Nawawi Hadis no. 15: Akhlak sosial seorang muslim",
    sortOrder: 15,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 33,
    title: "Berusaha mengendalikan amarah",
    materi: "Arbain An-Nawawi Hadis no. 16: Menahan marah",
    sortOrder: 16,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 34,
    title: "Berusaha ihsan (melakukan yang terbaik) dalam segala hal",
    materi: "Arbain An-Nawawi Hadis no. 17: Profesionalitas dalam Islam",
    sortOrder: 17,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 35,
    title: "Berusaha menghapus dosa dengan melakukan amal kebaikan",
    materi: "Arbain An-Nawawi Hadis no. 18: Takwa dan akhlak",
    sortOrder: 18,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 37,
    title: "Menjaga harga diri dengan sikap malu",
    materi: "Arbain An-Nawawi Hadis no. 20: Rasa malu",
    sortOrder: 19,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 41,
    title: "Tidak meminta-minta kepada manusia",
    materi: "Arbain An-Nawawi Hadis no. 24: Hanya Allah swt. tempat bergantung",
    sortOrder: 20,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 42,
    title: "Memaksimalkan potensi diri untuk melakukan amal kebaikan",
    materi: "Arbain An-Nawawi Hadis no. 25: Jenis-jenis sedekah selain dengan harta",
    sortOrder: 21,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 51,
    title: "Menghindari tabarruj, ikhtilat, dan khalwat",
    materi: "Menghindari tabarruj, ikhtilat, dan khalwat",
    sortOrder: 22,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 52,
    title: "Menyesuaikan diri dalam berpakaian",
    materi: "Menutup aurat",
    sortOrder: 23,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 54,
    title: "Membiasakan infak dan sedekah",
    materi: "Infak dan sedekah",
    sortOrder: 24,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 70,
    title: "Berusaha melaksanakan shalat sunah rawatib dan dhuha",
    materi: "Memelihara pelaksanaan sunah",
    sortOrder: 25,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 71,
    title: "Menjaga lisan, pandangan, dan memelihara kemaluan",
    materi: "Menjaga lisan, pandangan, dan kemaluan",
    sortOrder: 26,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 73,
    title: "Tidak membicarakan aib orang lain",
    materi: "Ghibah dan namimah",
    sortOrder: 27,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 74,
    title: "Bersikap jujur",
    materi: "Ash-shidqu",
    sortOrder: 28,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 76,
    title: "Aktif dalam kerja dakwah secara kolektif",
    materi: "Kerja kolektif dalam dakwah",
    sortOrder: 29,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.PRIMER,
    number: 77,
    title: "Bersilaturahim kepada keluarga, kerabat, teman, dan tokoh",
    materi: "Silaturahim",
    sortOrder: 30,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 3,
    title: "Mengambil inspirasi dari kehidupan ulama tafsir Ibnu Katsir dan Jalalain",
    materi: "Biografi ulama tafsir",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 5,
    title: "Memahami keagungan dan kesempurnaan ciptaan Allah swt.",
    materi: "Surat An-Naba ayat 1-16: Kekuasaan Allah swt. atas alam semesta",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 6,
    title: "Mengetahui balasan di akhirat bagi orang yang durhaka",
    materi: "Surat An-Naba ayat 17-30: Menyingkap akan hakikat berita besar",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 7,
    title: "Mengetahui balasan bagi orang yang bertakwa",
    materi: "Surat An-Naba ayat 31-40: Kemenangan orang yang bertakwa",
    sortOrder: 4,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 8,
    title: "Meyakini kepastian datangnya hari kebangkitan",
    materi: "Surat An-Naziat ayat 1-14: Kondisi orang yang mengingkari hari kebangkitan",
    sortOrder: 5,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 9,
    title: "Terlibat dalam aktivitas dakwah",
    materi: "Surat An-Naziat ayat 15-33: Optimistis pada kemenangan dakwah",
    sortOrder: 6,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 12,
    title: "Memahami objek dakwah",
    materi: "Surat Abasa ayat 1-16: Metode dakwah Rasulullah saw.  \nSurat Abasa ayat 17-32: Manusia yang tidak tahu hakikat dirinya \nSurat Abasa ayat 33-40: Dahsyatnya peristiwa hari kiamat",
    sortOrder: 7,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 14,
    title: "Menjadikan Alquran sebagai pedoman hidup",
    materi: "Surat At-Takwir ayat 15-29: Hakikat wahyu dan sifat Nabi Muhammad saw.",
    sortOrder: 8,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 15,
    title: "Tidak silau dengan urusan duniawi",
    materi: "Surat Al-Infithar: Tidak tertipu oleh dunia",
    sortOrder: 9,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 17,
    title: "Meyakini balasan atas perbuatan manusia di akhirat",
    materi: "Surat Al-Insyiqaq: Hakikat hidup manusia",
    sortOrder: 10,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 18,
    title: "Memahami adanya ujian keteguhan iman",
    materi: "Surat Al-Buruj: Keteguhan orang beriman",
    sortOrder: 11,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 19,
    title: "Meyakini perlindungan Allah swt. dari tipu daya orang kafir",
    materi: "Surat Ath-Thariq: Penjagaan Allah swt.",
    sortOrder: 12,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 21,
    title: "Berusaha mengamalkan amalan-amalan ahli surga",
    materi: "Surat Al-Ghasyiyah: Amalan-amalan ahli surga",
    sortOrder: 13,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 22,
    title: "Memahami kehidupan sebagai ujian",
    materi: "Surat Al-Fajar: Tabiat jiwa manusia",
    sortOrder: 14,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 4,
    title: "Mampu mengambil inspirasi dari peristiwa masa lalu",
    materi: "Surat As-Syams: Mengambil pelajaran masa lalu",
    sortOrder: 15,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 26,
    title: "Mengetahui kedudukan hadis",
    materi: "Ilmu hadis",
    sortOrder: 16,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 31,
    title: "Mengetahui jaminan hidup dalam Islam",
    materi: "Arbain An-Nawawi Hadis no. 14: Jaminan hidup dalam Islam",
    sortOrder: 17,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 36,
    title: "Menyakini penjagaan Allah swt. kepada hamba yang beriman",
    materi: "Arbain An-Nawawi Hadis no. 19: Menjaga Allah swt. maka Allah swt. akan menjagamu",
    sortOrder: 18,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 38,
    title: "Berusaha istiqomah dalam menjalankan perintah Allah swt. dan Rasul-Nya",
    materi: "Arbain An-Nawawi Hadis no. 21: Iman dan istiqomah",
    sortOrder: 19,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 39,
    title: "Berusaha komitmen dalam menjalankan ajaran Islam",
    materi: "Arbain An-Nawawi Hadis no. 22: Komitmen dengan ajaran Islam",
    sortOrder: 20,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 40,
    title: "Mengetahui perbuatan-perbuatan yang dapat menaikkan derajat diri manusia",
    materi: "Arbain An-Nawawi Hadis no. 23: Hakikat perbuatan manusia",
    sortOrder: 21,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 43,
    title: "Mengetahui iman kepada malaikat",
    materi: "Beriman kepada malaikat",
    sortOrder: 22,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 44,
    title: "Mengetahui iman kepada hari akhir",
    materi: "Beriman kepada hari akhir",
    sortOrder: 23,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 45,
    title: "Mengetahui iman kepada qadha dan qadar",
    materi: "Beriman kepada qadha dan qadar",
    sortOrder: 24,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 46,
    title: "Mengetahui tujuan dan peran penciptaan manusia",
    materi: "Penciptaan manusia; Peran manusia",
    sortOrder: 25,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 47,
    title: "Berusaha menghafal dan berdoa dengan asmaul husna",
    materi: "Asmaul Husna; Berdoa dengan Asmaul Husna",
    sortOrder: 26,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 48,
    title: "Mengetahui hukum taklif",
    materi: "Hukum taklifi dan wadh'i",
    sortOrder: 27,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 49,
    title: "Mengetahui fikih muamalah",
    materi: "Dasar-dasar fikih mualamah",
    sortOrder: 28,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 50,
    title: "Mengetahui fikih nikah",
    materi: "Fikih nikah",
    sortOrder: 29,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 53,
    title: "Memahami keutamaan berusaha dan berpenghasilan",
    materi: "Keutamaan berusaha dan punya penghasilan",
    sortOrder: 30,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 55,
    title: "Mengetahui dakwah secara terbuka yang dilakukan Nabi Muhammad saw.",
    materi: "Dakwah secara terbuka di Mekkah",
    sortOrder: 31,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 56,
    title: "Mengetahui peristiwa seputar hijrah Nabi Muhammad saw.",
    materi: "Peristiwa Hijrah; Pilar-pilar membangun masyarakat madani",
    sortOrder: 32,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 57,
    title: "Mengetahui peristiwa perubahan arah kiblat",
    materi: "Peristiwa perubahan arah kiblat",
    sortOrder: 33,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 58,
    title: "Mengetahui Peristiwa Badar",
    materi: "Peristiwa Badar",
    sortOrder: 34,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 59,
    title: "Mengetahui Peristiwa Uhud",
    materi: "Peristiwa Uhud",
    sortOrder: 35,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 60,
    title: "Mengetahui Peristiwa Khandaq",
    materi: "Peristiwa Khandaq",
    sortOrder: 36,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 61,
    title: "Mengetahui Peristiwa Hudaibiyah",
    materi: "Peristiwa Hudaibiyah",
    sortOrder: 37,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 62,
    title: "Mengetahui korespondensi dakwah Nabi Muhammad saw.",
    materi: "Korespondensi Nabi Muhammad saw. kepada penguasa-penguasa sekitar Jazirah Arab",
    sortOrder: 38,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 63,
    title: "Mengetahui Peristiwa Khaibar",
    materi: "Peristiwa Khaibar",
    sortOrder: 39,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 64,
    title: "Mengetahui Peristiwa Mu'tah",
    materi: "Peristiwa Mu'tah",
    sortOrder: 40,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 65,
    title: "Mengetahui Pembebasan Kota Mekkah",
    materi: "Pembebasan Kota Mekkah",
    sortOrder: 41,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 66,
    title: "Mengetahui Peristiwa Hunain",
    materi: "Perisitwa Hunain",
    sortOrder: 42,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 67,
    title: "Mengetahui Peristiwa Tabuk",
    materi: "Peristiwa Tabuk",
    sortOrder: 43,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 68,
    title: "Mengetahui Peristiwa Haji Wada'",
    materi: "Haji Wada'",
    sortOrder: 44,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 69,
    title: "Membaca wirid ayat-ayat Alquran tentang iman",
    materi: "Ayat-ayat Alquran tentang iman (bagian satu); Ayat-ayat Alquran tentang iman (bagian dua)",
    sortOrder: 45,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 72,
    title: "Berusaha menghafal doa-doa sesuai dengan peristiwa tertentu",
    materi: "Doa-doa saat peristiwa tertentu",
    sortOrder: 46,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 75,
    title: "Memahami kaidah-kaidah dakwah",
    materi: "Kaidah dakwah",
    sortOrder: 47,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEAGAMAAN,
    type: ICType.SEKUNDER,
    number: 78,
    title: "Mengetahui ragam pemikiran dalam dakwah",
    materi: "Aliran pemikiran dalam dakwah",
    sortOrder: 48,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEBANGSAAN,
    type: ICType.PRIMER,
    number: 79,
    title: "Mengetahui konsep musyawarah",
    materi: "Konsep musyawarah",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEBANGSAAN,
    type: ICType.PRIMER,
    number: 80,
    title: "Memahami Pancasila sebagai pandangan hidup bangsa",
    materi: "Pancasila sebagai pandangan hidup bangsa",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEBANGSAAN,
    type: ICType.PRIMER,
    number: 81,
    title: "Mengetahui Konsep NKRI",
    materi: "Negara Kesatuan Republik Indonesia (NKRI)",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEBANGSAAN,
    type: ICType.PRIMER,
    number: 84,
    title: "Tidak bersikap radikal",
    materi: "Bahaya radikalisme",
    sortOrder: 4,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEBANGSAAN,
    type: ICType.SEKUNDER,
    number: 82,
    title: "Mengetahui tujuan negara dalam Pembukaan UUD NRI 1945",
    materi: "Tujuan negara dalam Pembukaan UUD NRI 1945",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEBANGSAAN,
    type: ICType.SEKUNDER,
    number: 83,
    title: "Mengetahui tentang Hak Asasi Manusia",
    materi: "Hak Asasi Manusia",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEBANGSAAN,
    type: ICType.SEKUNDER,
    number: 85,
    title: "Mengetahui dampak korupsi terhadap negara",
    materi: "Korupsi menghancurkan negara",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEBANGSAAN,
    type: ICType.SEKUNDER,
    number: 86,
    title: "Mengetahui peran politik pemuda",
    materi: "Peran politik pemuda",
    sortOrder: 4,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEMASYARAKATAN,
    type: ICType.PRIMER,
    number: 87,
    title: "Menunjukkan perilaku yang baik dalam bermasyarakat",
    materi: "Seni bergaul dengan masyarakat",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEMASYARAKATAN,
    type: ICType.PRIMER,
    number: 89,
    title: "Membantu kerja-kerja kerelawanan",
    materi: "Kerja kerelawanan di masyarakat",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEMASYARAKATAN,
    type: ICType.SEKUNDER,
    number: 88,
    title: "Berinteraksi dengan tokoh sekitar",
    materi: "Teknik membangun komunikasi dengan tokoh masyarakat",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEMASYARAKATAN,
    type: ICType.SEKUNDER,
    number: 90,
    title: "Mengetahui keragaman budaya",
    materi: "Keragaman budaya",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEMASYARAKATAN,
    type: ICType.SEKUNDER,
    number: 91,
    title: "Berusaha memiliki visi misi berkeluarga",
    materi: "Membangun keluarga harmonis",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEORGANISASIAN,
    type: ICType.PRIMER,
    number: 95,
    title: "Berusaha berolah raga secara rutin minimal 30 menit setiap hari",
    materi: "Merutinkan olah raga dan menjaga kebugaran",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEORGANISASIAN,
    type: ICType.PRIMER,
    number: 96,
    title: "Siap menjadi Fasilitator",
    materi: "Pelatihan Penyiapan Fasilitator UPA",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEORGANISASIAN,
    type: ICType.PRIMER,
    number: 97,
    title: "Berusaha menjadi Pembina",
    materi: "Pelatihan Penyiapan Pembina UPA",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEORGANISASIAN,
    type: ICType.SEKUNDER,
    number: 92,
    title: "Terlibat kegiatan yang diselenggarakan oleh Organisasi",
    materi: "Terlibat dalam kegiatan Organisasi",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEORGANISASIAN,
    type: ICType.SEKUNDER,
    number: 93,
    title: "Hadir di program Pembinaan minimal 80%",
    materi: "Kiat-kiat sukses mengikuti kegiatan Kaderisasi untuk Anggota",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEORGANISASIAN,
    type: ICType.SEKUNDER,
    number: 94,
    title: "Hadir di program Pelatihan minimal 80%",
    materi: null,
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.PRIMER,
    number: 102,
    title: "Mampu membuat perencanaan diri untuk hidup lebih produktif",
    materi: "Pribadi produktif dan bermanfaat",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.PRIMER,
    number: 103,
    title: "Mampu memverifikasi data dan informasi yang diterima",
    materi: "Kecerdasan literasi",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.PRIMER,
    number: 105,
    title: "Berusaha melakukan komunikasi efektif",
    materi: "Komunikasi efektif",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.SEKUNDER,
    number: 98,
    title: "Mampu berbahasa Indonesia dan Daerah",
    materi: "Bahasa Indonesia dan Bahasa Daerah",
    sortOrder: 1,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.SEKUNDER,
    number: 99,
    title: "Mengenal bahasa asing tingkat dasar",
    materi: "Salah satu bahasa asing tingkat dasar",
    sortOrder: 2,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.SEKUNDER,
    number: 100,
    title: "Mengetahui ruang lingkup kepemimpinan dalam tim",
    materi: "Kepemimpinan dalam tim",
    sortOrder: 3,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.SEKUNDER,
    number: 101,
    title: "Mengetahui cara mengelola waktu yang efektif",
    materi: "Manajemen waktu",
    sortOrder: 4,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.SEKUNDER,
    number: 104,
    title: "Mampu menggunakan media sosial dengan bijaksana",
    materi: "Etika bermedia sosial",
    sortOrder: 5,
  },
  {
    level: GroupLevel.LEVEL_2,
    category: ICCategory.KEPEMIMPINAN_KEWIRAUSAHAAN,
    type: ICType.SEKUNDER,
    number: 106,
    title: "Mengetahui model bisnis yang sesuai dengan kebutuhan",
    materi: "Model bisnis",
    sortOrder: 6,
  },
];
